0.04s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
c:\Users\haibi\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\_vendored\force_pydevd.py:18: UserWarning: incompatible copy of pydevd already imported:
 d:\anaconda3\envs\data\envs\py3.11\Lib\site-packages\pydevd_plugins\extensions\pydevd_plugin_omegaconf.py
  warnings.warn(msg + ':\n {}'.format('\n  '.join(_unvendored)))
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1078, in _find_spec
  File "d:\anaconda3\envs\data\envs\py3.11\Lib\site-packages\_distutils_hack\__init__.py", line 110, in find_spec
    return method()
           ^^^^^^^^
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_pydevd_bundle\\pydevd_cython.pyx", line 2020, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__
MemoryError
Traceback (most recent call last):
