[*] Running ...
[*] Dataset loaded: E:\all_works\iclr2025\AEL-P-SNE(1)\AEL-P-SNE/problems/tsp_pomo\dataset\train50_dataset.npy with 5 instances.
Traceback (most recent call last):
  File "E:\all_works\iclr2025\AEL-P-SNE(1)\AEL-P-SNE/problems/tsp_pomo/eval.py", line 56, in <module>
    obj = search_routine(cal_total_distance,distance_matrix,20,100)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\all_works\iclr2025\AEL-P-SNE(1)\AEL-P-SNE\problems\tsp_pomo\generated\iter_num_1_func_index_3_response_id_52.py", line 115, in search_routine
    child1 = crossover(parent1, parent2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\all_works\iclr2025\AEL-P-SNE(1)\AEL-P-SNE\problems\tsp_pomo\generated\iter_num_1_func_index_3_response_id_52.py", line 71, in crossover
    while parent2[parent2_index] in child:
          ~~~~~~~^^^^^^^^^^^^^^^
IndexError: index 50 is out of bounds for axis 0 with size 50
