0.02s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
c:\Users\haibi\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\_vendored\force_pydevd.py:18: UserWarning: incompatible copy of pydevd already imported:
 d:\anaconda3\envs\data\envs\py3.11\Lib\site-packages\pydevd_plugins\extensions\pydevd_plugin_omegaconf.py
  warnings.warn(msg + ':\n {}'.format('\n  '.join(_unvendored)))
[*] Running ...
[*] Dataset loaded: e:\all_works\iclr2025\AEL-P-SNE(1)\AEL-P-SNE/problems/tsp_pomo\dataset\train200_dataset.npy with 5 instances.
[*] Instance 0: 97.92298898461296
[*] Instance 1: 108.23659534538885
[*] Instance 2: 97.9435933847571
[*] Instance 3: 102.43674492104853
[*] Instance 4: 103.95746408047845
[*] Average:
102.09947734325718
